## node configurations
node:
  ## the type of crust: authority/full
  chain: "full"
  ## the type of sworker: disable/enable
  sworker: "enable"
  ## the type of smanager: disable/isolation/member
  smanager: "member"
  ## the type of ipfs: disable/enable
  ipfs: "enable"

## identity configurations
identity:
  ## the backup of chain account
  backup: '{"address":"5CaD2AGGYwugY5dRtiwcanBprxveKd7iBNDz9jRYudVtJ78S","encoded":"KeZkmq9exbJe+E/GHeEwTgjW9MNNbg/J60OfKYqla7cAgAAAAQAAAAgAAABzfqfktehZry8t5q9tBwIDbRlhZ8ME1r68RiaK8ogRAEEggVE3AY71WU0wLzt8lU/Hg2txpleIXmwM1dBD5wgkAoz2Si8v2/HYdR/7a4axt+HGBjFkrNUTrVAvp1Jt691YRkPG1GJTvXqHOcuNu28at3nG/DGc/TrIunSG/E0I08W84/Kq1IYXNbnigSZsLNxzMuWvP/b5cKArxFNb","encoding":{"content":["pkcs8","sr25519"],"type":["scrypt","xsalsa20-poly1305"],"version":"3"},"meta":{"genesisHash":"0xb19e8874eb2013dc100534fafa322e105eea53c0aa02cd17cf94a2df35fbd41f","name":"controller118","tags":[],"whenCreated":1611738039812}}'
  ## the password of chain account
  password: "123"

## chain configurations
chain:
  ## the name of chain node
  name: "crust-node"
